import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8');
const root = await read('site/index.html');
const foundry = await read('site/works/siso-foundry/index.html');
const dossier = JSON.parse(await read('site/works/siso-foundry/index.json'));
const source = JSON.parse(await read('registry/works/siso-foundry.json'));
assert.deepEqual(dossier.reading, source.reading);
assert.equal(dossier.relationships.length, source.relationships.length);
assert.equal((root.match(/<a href="[^"]+" aria-label="(?:Client outcomes|Owners \+ compute|Packs \+ code|The Library|People \+ repositories|Foundry|God Questions|Better systems)">/g) || []).length, 8);
assert.equal((root.match(/class="siso-rail"/g) || []).length, 1);
assert.equal((foundry.match(/class="siso-rail"/g) || []).length, 1);
assert.equal((root.match(/<h1>/g) || []).length, 1);
for (const heading of ['Why it matters', 'How it links', 'Sauce', 'For agents', 'Evidence &amp; receipts']) assert.ok(foundry.includes(heading), heading);
for (const relation of dossier.relationships) assert.ok(foundry.includes(relation.target_library_url));
assert.ok(!(await read('site/works/siso-knowledge/index.html')).includes('class="siso-rail"'), 'Only the opted-in Work gets the pilot');
assert.ok(dossier.selected_release.id, 'Existing selected Release remains present');
assert.ok(root.includes('data-catalog'), 'Existing search and filter consumer preserved');
console.log('PASS reading surface: source/dossier parity, eight linked loop nodes, pilot isolation, existing release and catalog contracts');
